name: Deploy to Staging
on: 
    workflow_run:
        workflows: [Build Docker Image]
        types:
          - completed
env:
    RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
jobs:
    deploy-stage:
        runs-on: ubuntu-latest
        steps:
            - name: Login to GHCR
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            - name: Pull Docker Image
              run: docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}
            - name: Install Railway CLI
              run: npm install -g @railway/cli
            - name: Deploy to Staging
              run: railway deploy --image ghcr.io/${{ github.repository }}:${{ github.sha }}