name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types: [completed]  


jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Trigger Render Production Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_PRODUCTION_HOOK }}