name: Deploy to Production

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Production Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_PRODUCTION_HOOK }}
